<?xml version="1.0"?>
<package format="3">
  <name>orbslam3_ros2</name>
  <version>0.0.1</version>
  <description>ROS 2 wrapper for ORB-SLAM3 RGB-D inertial tracking.</description>
  <maintainer email="baggio@todo.todo">baggio</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>message_filters</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
